//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenimiento.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Oficina
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Oficina()
        {
            this.Empleadoes = new HashSet<Empleado>();
        }
    
        public int idoficina { get; set; }
        [Required]
        [Display(Name = "Ingrese Descripcion")]
        public string descripcion { get; set; }
        [Required]
        [Display(Name = "Ingrese Telefono")]
        public string telefono { get; set; }
        [Required]
        [Display(Name = "Ingrese Direccion")]
        public string direccion { get; set; }
        [Required]
        [Display(Name = "Ingrese Nombre")]
        public string nombreofi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Empleado> Empleadoes { get; set; }
    }
}
